title: "Neha Simon"
email: nehasimon67@gmail.com
description: "Data scientist | Bioinformatics & Genomics | AI/ML Enthusiast"
github_username: nehasimon
baseurl: ""
url: "https://nehasimon.github.io"
theme: jekyll-theme-minimal

buttons:
  - label: "Resume"
    url: "assets/Neha_Simon_bioinformatician.pdf"
  - label: "Work Samples"
    url: "/samples.html"
